### ISSUE TITLE
Second Release

### ISSUE THREAD

**Issue by GuyNoimark** [GuyNoimark/where-is-efi#18]
- [x] Change the countdown timer to a stopwatch
- [x] #19
- [x] Search for LAN based JSON storage

**Comment by Ido-Sobol** [comment]
> * [ ]  Change the countdown timer to a stopwatch
@GuyNoimark  do we need to keep the time at the end or just reverse it?

**Comment by GuyNoimark** [comment]
> > * [ ]  Change the countdown timer to a stopwatch
> 
> @GuyNoimark  do we need to keep the time at the end or just reverse it?
> 
> 
> 
> 

What do you mean?
We do need to save the amount of time the user spent answering the questions

**Comment by Ido-Sobol** [comment]
> > > * [ ]   Change the countdown timer to a stopwatch
> > 
> > 
> > @GuyNoimark  do we need to keep the time at the end or just reverse it?
> 
> What do you mean? We do need to save the amount of time the user spent answering the questions

For each question separatly or the total time?

**Comment by GuyNoimark** [comment]
I think total will do
